### ISSUE TITLE
Allow null values for args?

### ISSUE THREAD

**Issue by dylan-baskind** [latos/heroin-js#5]
Previous versions of heroin allowed something like:

```coffeescript
make SomeClassCtor,
		thing: "stuff"
		anotherArg: obj.notAProperty
```
i.e. where obj.notAProperty is null

With latest version of heroin, we have to provide explicit non-null defaults during instantiation:

```coffeescript
make SomeCtrl,
		thing: "stuff"
		anotherArg: obj.notAProperty or ""
```

Often I do want an arg to have a possible null value.

Possible to allow explicitly set null values as args?

**Comment by latos** [comment]
Null should work - undefined is what it doesn't allow.

If null doesn't work then that's a bug?

**Comment by dylan-baskind** [comment]
Yep that distinction does make sense. Closing this issue.
